### ISSUE TITLE
dims 未声明的标识符

### ISSUE THREAD

**Issue by ghost** [FengZhiheng-coder/paddleOCR_cpp_tensorrt#1]
代码:
 context->setOptimizationProfileAsync(0, stream); // 让convert.h创建engine的动态输入配置生效
nvinfer1::Dims dims = context->getBindingDimensions(inputIndex); //获取带有可变维度的输入维度信息
dims.d[0] = 1;
dims.d[2] = resize_img.rows;
dims.d[3] = resize_img.cols;

报错：C2065 “dims”:未声明的标识符

win10

**Comment by fzhiheng** [comment]
代码的测试环境是ubuntu18.04，Clion2021.3.4，windows的话，你要是修改了det.cpp这个文件，可以把修改的内容发一下，或者使用cat -A检查一下是否引入了莫名其妙的字符。

**Comment by fzhiheng** [comment]
> ```
>  代码:
> ```
> 
> context->setOptimizationProfileAsync(0, stream); // 让convert.h创建engine的动态输入配置生效 nvinfer1::Dims dims = context->getBindingDimensions(inputIndex); //获取带有可变维度的输入维度信息 dims.d[0] = 1; dims.d[2] = resize_img.rows; dims.d[3] = resize_img.cols;
> 
> 报错：C2065 “dims”:未声明的标识符
> 
> win10

代码的测试环境是ubuntu18.04，Clion2021.3.4，windows的话，你要是修改了det.cpp这个文件，可以把修改的内容发一下，或者使用cat -A检查一下是否引入了莫名其妙的字符。

**Comment by ghost** [comment]
void* buffers[2];
        // 为buffer[0]指针（输入）定义空间大小
        int data_size = 1 * 3 * resize_img.rows * resize_img.cols;
        float *inBlob = new float[data_size];
        this->permute_op_.Run(&resize_img, inBlob);

        int inputIndex = 0;
        CHECK(cudaMalloc(&buffers[inputIndex], data_size * sizeof(float)));
        
        auto inference_start = std::chrono::steady_clock::now();
        // Create stream
        cudaStream_t stream;
        CHECK(cudaStreamCreate(&stream));
        // 将数据放到gpu上
        CHECK(cudaMemcpyAsync(buffers[inputIndex], inBlob, data_size * sizeof(float), cudaMemcpyHostToDevice, stream));

        context->setOptimizationProfileAsync(0, stream); // 让convert.h创建engine的动态输入配置生效
        auto dims = context->getBindingDimensions(inputIndex); //获取带有可变维度的输入维度信息
        dims.d[0] = 1;
        dims.d[2] = resize_img.rows;
        dims.d[2] = resize_img.rows;
        dims.d[3] = resize_img.cols;
        
        context->setBindingDimensions(inputIndex, dims); // 根据输入图像大小更新输入维度

代码仅仅只是修改了语法和编译环境

**Comment by fzhiheng** [comment]
> void* buffers[2]; // 为buffer[0]指针（输入）定义空间大小 int data_size = 1 * 3 * resize_img.rows * resize_img.cols; float *inBlob = new float[data_size]; this->permute_op_.Run(&resize_img, inBlob);
> 
> ```
>     int inputIndex = 0;
>     CHECK(cudaMalloc(&buffers[inputIndex], data_size * sizeof(float)));
>     
>     auto inference_start = std::chrono::steady_clock::now();
>     // Create stream
>     cudaStream_t stream;
>     CHECK(cudaStreamCreate(&stream));
>     // 将数据放到gpu上
>     CHECK(cudaMemcpyAsync(buffers[inputIndex], inBlob, data_size * sizeof(float), cudaMemcpyHostToDevice, stream));
> 
>     context->setOptimizationProfileAsync(0, stream); // 让convert.h创建engine的动态输入配置生效
>     auto dims = context->getBindingDimensions(inputIndex); //获取带有可变维度的输入维度信息
>     dims.d[0] = 1;
>     dims.d[2] = resize_img.rows;
>     dims.d[2] = resize_img.rows;
>     dims.d[3] = resize_img.cols;
>     
>     context->setBindingDimensions(inputIndex, dims); // 根据输入图像大小更新输入维度
> ```
> 
> 代码仅仅只是修改了语法和编译环境

在ubuntu18.04的环境下测试是没有问题的。不修改的话可以运行成功吗？

**Comment by ghost** [comment]
感谢您的付出，我这边已经解决了

**Comment by fzhiheng** [comment]
> 感谢您的付出，我这边已经解决了

请问是仓库中代码的问题吗？还是修改后的代码的问题。

**Comment by ghost** [comment]
编译环境不一样，win 这边需要修改一下编码格式

**Comment by ghost** [comment]
仓库代码目前没有遇到，后续遇到再给您答复
