### ISSUE TITLE
模型转换出错

### ISSUE THREAD

**Issue by clancylian** [FengZhiheng-coder/paddleOCR_cpp_tensorrt#4]
`
./build/ocr --build_precision="fp16" --det_onnx_dir="../myModels/det.onnx" --rec_onnx_dir="../myModels/ch_rec_v3.onnx" --save_engine_dir="../myEngines/" --rec_char_dict_path="../myModels/dict_txt/ppocr_keys_v1.txt" --rec_batch_num=1 --det=true --cls=false --rec=true  --image_dir="./testImgs/11.jpg" --output="./output/"

[../myEngines/det_fp162.engine] does not exist, we will use [../myModels/det.onnx] to build engine.
Could not open file ../myModels/det.onnx
Could not open file ../myModels/det.onnx
[01/10/2023-01:58:38] [E] [TRT] ModelImporter.cpp:735: Failed to parse ONNX model from file: ../myModels/det.onnx
ERROR: could not parse input engine.
 error in build engine from onnx
no such label file: ../myModels/dict_txt/ppocr_keys_v1.txt, exit the program...

`

**Comment by fzhiheng** [comment]
use `./build/ocr --build_precision="fp16" --det_onnx_dir="./myModels/det.onnx" --rec_onnx_dir="./myModels/ch_rec_v3.onnx" --save_engine_dir="./myEngines/" --rec_char_dict_path="./myModels/dict_txt/ppocr_keys_v1.txt" --rec_batch_num=1 --det=true --cls=false --rec=true --image_dir="./testImgs/11.jpg" --output="./output/"` or switch paths to absolute paths
